import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/layout/Header";
import Background from "./components/layout/Background";
import SmoothScroll from "./components/layout/SmoothScroll";
import Footer from "./components/layout/footer";
import MoreOptions from "./components/layout/moreOptions";
import FixedSidebar from "./components/layout/FixedSidebar";

const arial = localFont({
  src: "../public/fonts/arial.ttf",
  variable: "--font-arial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arial.variable} antialiased`}
      >
        <SmoothScroll />
        {/* <Background /> */}
        <Header />
        <FixedSidebar />
        <div className="">
          {children}
        </div>
        <Footer />
        <MoreOptions />
      </body>
    </html>
  );
}
